-- Main Categories
INSERT INTO categories (category_id, name) VALUES (1, 'Компьютеры и комплектующие');
INSERT INTO categories (category_id, name) VALUES (2, 'Бытовая техника для дома и кухни');
INSERT INTO categories (category_id, name) VALUES (3, 'Смартфоны и мобильные устройства');
INSERT INTO categories (category_id, name) VALUES (4, 'Телевизоры и мультимедиа');
INSERT INTO categories (category_id, name) VALUES (5, 'Уход за собой и красота');
INSERT INTO categories (category_id, name) VALUES (6, 'Аудио и звуковая техника');
INSERT INTO categories (category_id, name) VALUES (7, 'Умный дом и электроника');
INSERT INTO categories (category_id, name) VALUES (8, 'Массаж и здоровье');
INSERT INTO categories (category_id, name) VALUES (9, 'Аксессуары');
INSERT INTO categories (category_id, name) VALUES (10, 'Авто-электроника и гаджеты');

-- SubCategories
INSERT INTO categories (category_id, name, parent_id) VALUES (11, 'Настольные компьютеры', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (12, 'Ноутбуки', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (13, 'Процессоры', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (14, 'Оперативная память', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (15, 'SSD-накопители', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (16, 'Системы охлаждения', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (17, 'Блоки питания', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (18, 'Материнские платы', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (19, 'Корпуса', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (20, 'Кабели и переходники', 1);
INSERT INTO categories (category_id, name, parent_id) VALUES (21, 'Стиральные машины', 2);
INSERT INTO categories (category_id, name, parent_id) VALUES (22, 'Сушильные машины', 2);
INSERT INTO categories (category_id, name, parent_id) VALUES (23, 'Кондиционеры и вентиляторы', 2);
INSERT INTO categories (category_id, name, parent_id) VALUES (24, 'Обогреватели', 2);
INSERT INTO categories (category_id, name, parent_id) VALUES (25, 'Техника для уборки', 2);
INSERT INTO categories (category_id, name, parent_id) VALUES (26, 'Водонагреватели', 2);
INSERT INTO categories (category_id, name, parent_id) VALUES (27, 'Очистка воды и уход за одеждой', 2);
INSERT INTO categories (category_id, name, parent_id) VALUES (28, 'Смартфоны', 3);
INSERT INTO categories (category_id, name, parent_id) VALUES (29, 'Аксессуары для телефонов', 3);
INSERT INTO categories (category_id, name, parent_id) VALUES (30, 'Телевизоры', 4);
INSERT INTO categories (category_id, name, parent_id) VALUES (31, 'Саундбары', 4);
INSERT INTO categories (category_id, name, parent_id) VALUES (32, 'Медиаплееры и приставки', 4);
INSERT INTO categories (category_id, name, parent_id) VALUES (33, 'Приставки для цифрового ТВ', 4);
INSERT INTO categories (category_id, name, parent_id) VALUES (34, 'Фены', 5);
INSERT INTO categories (category_id, name, parent_id) VALUES (35, 'Утюги для одежды', 5);
INSERT INTO categories (category_id, name, parent_id) VALUES (36, 'Стайлеры, плойки и выпрямители для волос', 5);
INSERT INTO categories (category_id, name, parent_id) VALUES (37, 'Микрофоны', 6);
INSERT INTO categories (category_id, name, parent_id) VALUES (38, 'Колонки и акустика', 6);
INSERT INTO categories (category_id, name, parent_id) VALUES (39, 'Наушники', 6);
INSERT INTO categories (category_id, name, parent_id) VALUES (40, 'Умные лампы', 7);
INSERT INTO categories (category_id, name, parent_id) VALUES (41, 'Датчики умного дома', 7);
INSERT INTO categories (category_id, name, parent_id) VALUES (42, 'Умные розетки', 7);
INSERT INTO categories (category_id, name, parent_id) VALUES (43, 'Комплекты умного дома', 7);
INSERT INTO categories (category_id, name, parent_id) VALUES (44, 'Умные замки и гаджеты', 7);
INSERT INTO categories (category_id, name, parent_id) VALUES (45, 'Массажёры', 8);
INSERT INTO categories (category_id, name, parent_id) VALUES (46, 'Товары для здоровья и отдыха', 8);
INSERT INTO categories (category_id, name, parent_id) VALUES (47, 'Кабели, зарядные устройства', 9);
INSERT INTO categories (category_id, name, parent_id) VALUES (48, 'Компьютерные аксессуары', 9);
INSERT INTO categories (category_id, name, parent_id) VALUES (49, 'Чехлы и сумки', 9);
INSERT INTO categories (category_id, name, parent_id) VALUES (50, 'Навигация и авто-приставки', 10);


-- SubSubCategories
INSERT INTO categories (category_id, name, parent_id) VALUES (51, 'Мини-ПК и неттопы', 11);
INSERT INTO categories (category_id, name, parent_id) VALUES (52, 'Компьютеры в сборе', 11);
INSERT INTO categories (category_id, name, parent_id) VALUES (53, 'Игровые ПК', 11);
INSERT INTO categories (category_id, name, parent_id) VALUES (54, 'Рабочие станции', 11);
INSERT INTO categories (category_id, name, parent_id) VALUES (55, 'Игровые ноутбуки', 12);
INSERT INTO categories (category_id, name, parent_id) VALUES (56, 'Ультрабуки', 12);
INSERT INTO categories (category_id, name, parent_id) VALUES (57, 'Бюджетные ноутбуки', 12);
INSERT INTO categories (category_id, name, parent_id) VALUES (58, 'Ноутбуки для бизнеса', 12);
INSERT INTO categories (category_id, name, parent_id) VALUES (59, 'Фронтальные', 21);
INSERT INTO categories (category_id, name, parent_id) VALUES (60, 'Вертикальные', 21);
INSERT INTO categories (category_id, name, parent_id) VALUES (61, 'С сушкой', 21);
INSERT INTO categories (category_id, name, parent_id) VALUES (62, 'Android', 28);
INSERT INTO categories (category_id, name, parent_id) VALUES (63, 'iOS', 28);
INSERT INTO categories (category_id, name, parent_id) VALUES (64, 'Смартфоны с большой батареей', 28);
INSERT INTO categories (category_id, name, parent_id) VALUES (65, 'LED', 30);
INSERT INTO categories (category_id, name, parent_id) VALUES (66, 'OLED', 30);
INSERT INTO categories (category_id, name, parent_id) VALUES (67, 'QLED', 30);
INSERT INTO categories (category_id, name, parent_id) VALUES (68, 'Smart TV', 30);
INSERT INTO categories (category_id, name, parent_id) VALUES (69, 'Профессиональные микрофоны', 37);
INSERT INTO categories (category_id, name, parent_id) VALUES (70, 'Портативные колонки', 38);
INSERT INTO categories (category_id, name, parent_id) VALUES (71, 'Домашние акустические системы', 38);
INSERT INTO categories (category_id, name, parent_id) VALUES (72, 'Вкладыши', 39);
INSERT INTO categories (category_id, name, parent_id) VALUES (73, 'Полноразмерные наушники', 39);
INSERT INTO categories (category_id, name, parent_id) VALUES (74, 'Лампочки с Wi-Fi', 40);
INSERT INTO categories (category_id, name, parent_id) VALUES (75, 'Датчики движения', 41);
INSERT INTO categories (category_id, name, parent_id) VALUES (76, 'Розетки с таймером', 42);
INSERT INTO categories (category_id, name, parent_id) VALUES (77, 'Комплект умного дома для новичков', 43);
INSERT INTO categories (category_id, name, parent_id) VALUES (78, 'Умные дверные замки', 44);
INSERT INTO categories (category_id, name, parent_id) VALUES (79, 'Массажеры для шеи и спины', 45);
INSERT INTO categories (category_id, name, parent_id) VALUES (80, 'Роликовые массажеры', 45);
INSERT INTO categories (category_id, name, parent_id) VALUES (81, 'Товары для фитнеса', 46);
INSERT INTO categories (category_id, name, parent_id) VALUES (82, 'Релакс и отдых', 46);
INSERT INTO categories (category_id, name, parent_id) VALUES (83, 'USB кабели', 47);
INSERT INTO categories (category_id, name, parent_id) VALUES (84, 'Портативные зарядные устройства', 47);
INSERT INTO categories (category_id, name, parent_id) VALUES (85, 'Клавиатуры и мыши', 48);
INSERT INTO categories (category_id, name, parent_id) VALUES (86, 'Сумки и рюкзаки для ноутбуков', 49);
INSERT INTO categories (category_id, name, parent_id) VALUES (87, 'Навигаторы GPS', 50);
INSERT INTO categories (category_id, name, parent_id) VALUES (88, 'Видеорегистраторы', 50);
INSERT INTO categories (category_id, name, parent_id) VALUES (89, 'Парктроники и камеры заднего вида', 50);
