INSERT INTO clients (id, first_name, last_name, email, address) VALUES (1, 'Marnia', 'Krammer', 'mkrammer0@dagondesign.com', 'Room 691');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (2, 'Bastian', 'Boggas', 'bboggas1@e-recht24.de', 'Suite 40');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (3, 'Allister', 'Boreland', 'aboreland2@nps.gov', 'Suite 66');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (4, 'Clark', 'Deniskevich', 'cdeniskevich3@livejournal.com', 'PO Box 90941');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (5, 'Ellene', 'Pinare', 'epinare4@ucsd.edu', 'Suite 44');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (6, 'Gui', 'Boyland', 'gboyland5@w3.org', '14th Floor');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (7, 'Jenilee', 'Rhelton', 'jrhelton6@auda.org.au', 'Room 257');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (8, 'Marin', 'Peteri', 'mpeteri7@cyberchimps.com', 'PO Box 97982');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (9, 'Rochester', 'Maiden', 'rmaiden8@studiopress.com', 'Apt 1263');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (10, 'Odele', 'Tarquinio', 'otarquinio9@freewebs.com', 'Room 1000');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (11, 'Sharl', 'Lapenna', 'slapennaa@earthlink.net', '6th Floor');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (12, 'Lebbie', 'Domenichelli', 'ldomenichellib@furl.net', 'PO Box 64814');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (13, 'Cassaundra', 'MacCrachen', 'cmaccrachenc@trellian.com', '2nd Floor');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (14, 'Herschel', 'Dossetter', 'hdossetterd@house.gov', 'Apt 505');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (15, 'Giuditta', 'Vernalls', 'gvernallse@fotki.com', 'Suite 66');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (16, 'Demetris', 'Newhouse', 'dnewhousef@yale.edu', 'Room 763');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (17, 'Farah', 'Dornin', 'fdorning@ycombinator.com', 'Apt 176');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (18, 'Isabelle', 'Birtonshaw', 'ibirtonshawh@webnode.com', 'PO Box 23898');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (19, 'Willey', 'Bernhart', 'wbernharti@vimeo.com', 'PO Box 26961');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (20, 'Ondrea', 'Robins', 'orobinsj@domainmarket.com', 'Room 552');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (21, 'Cicely', 'Tyhurst', 'ctyhurstk@privacy.gov.au', 'PO Box 70639');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (22, 'Culley', 'Rizon', 'crizonl@wisc.edu', 'PO Box 95612');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (23, 'Jewelle', 'Bisseker', 'jbissekerm@chronoengine.com', 'PO Box 73864');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (24, 'Pearle', 'Tomsett', 'ptomsettn@comcast.net', 'Apt 1742');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (25, 'Miltie', 'Bachman', 'mbachmano@msn.com', 'Room 1844');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (26, 'Tabbie', 'Chappelle', 'tchappellep@shareasale.com', 'Suite 50');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (27, 'Luther', 'Keetch', 'lkeetchq@cafepress.com', 'Room 455');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (28, 'Gordan', 'Buckie', 'gbuckier@webeden.co.uk', 'Suite 47');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (29, 'Adria', 'Bowstead', 'abowsteads@walmart.com', 'Apt 1701');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (30, 'Norbert', 'St Pierre', 'nstpierret@1688.com', '5th Floor');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (31, 'Avictor', 'Murray', 'amurrayu@vistaprint.com', 'Apt 91');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (32, 'Rowney', 'Durnall', 'rdurnallv@china.com.cn', 'PO Box 82040');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (33, 'Sander', 'Crosswaite', 'scrosswaitew@bigcartel.com', 'Apt 999');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (34, 'Lauraine', 'Blaymires', 'lblaymiresx@senate.gov', 'Suite 58');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (35, 'Tades', 'Longwood', 'tlongwoody@addthis.com', 'Apt 370');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (36, 'Faina', 'Denisovich', 'fdenisovichz@a8.net', 'PO Box 56869');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (37, 'Eduino', 'MacCague', 'emaccague10@vkontakte.ru', 'Apt 1067');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (38, 'Yancy', 'Marling', 'ymarling11@senate.gov', '9th Floor');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (39, 'Banky', 'Ackenhead', 'backenhead12@state.tx.us', 'PO Box 52677');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (40, 'Alvira', 'Newstead', 'anewstead13@about.com', 'PO Box 64011');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (41, 'Sam', 'Choudhury', 'schoudhury14@amazon.co.uk', 'Room 1811');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (42, 'Monique', 'Dreghorn', 'mdreghorn15@ucoz.ru', 'Suite 67');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (43, 'Hector', 'Belvin', 'hbelvin16@live.com', 'Room 915');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (44, 'Freedman', 'Sisse', 'fsisse17@icio.us', '8th Floor');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (45, 'Valentina', 'Duckworth', 'vduckworth18@blogs.com', '5th Floor');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (46, 'Des', 'Bickers', 'dbickers19@histats.com', 'PO Box 17795');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (47, 'Cora', 'Duffree', 'cduffree1a@paginegialle.it', 'Room 278');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (48, 'Hamid', 'Lodin', 'hlodin1b@icq.com', 'Suite 71');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (49, 'Tammy', 'Liff', 'tliff1c@a8.net', 'Apt 1888');
INSERT INTO clients (id, first_name, last_name, email, address) VALUES (50, 'Horst', 'de Werk', 'hdewerk1d@springer.com', 'Room 342');